### ISSUE TITLE
Feature request: command to delete attribute(s)

### ISSUE THREAD

**Issue by sigio** [mahlonsmith/shelldap#4]
Hi,

Love shelldap... but there is one usecase where it doesn't seem to do what I want (maybe i'm missing something.

If I want to remove some attribute from an ldap object, I can use 'edit', then remove the line, and save, but this then results in the following message (and the attribute remaining):

For example, I have a field 'telexNumber', which I then comment or remove:
ou=People,~ > edit uid=sigio 
<edit my file, save>
No attributes to update
Edit again? [Yn]: 

Would be nice if there was something like:
removeattribute uid=sigio telexNumber 

Or if removing a field would trigger the correct ldap update 

dn: uid=sigio,ou=People,MUNGED
changetype: modify
delete: telexNumber

**Comment by sigio** [comment]
I've tried commenting the field, removeing it completely, and even replacing it with empty quotes or an empty string, but this doesn't seem to result in the field being removed.

**Comment by mahlonsmith** [comment]
This does appear to be something specific to that attribute, simply deleting the line should indeed be all you need to do, and other attributes do what you expect.

Doing some more digging - it looks like there's a specific SYNTAX used for "telexNumber", which might be a clue.  (1.3.6.1.4.1.1466.115.121.1.52)

**Comment by mahlonsmith** [comment]
There are two issues here -- one is definitely an edge case I missed in the LCS diffing.  The other is that shelldap can't know easily how to modify attributes that don't have an equality matching rule that aren't marked as SINGLE values.  Same deal for ldapmodify, if there are multiple values, they all must be removed.  The fix for this is to add an equality matcher in your core.schema server side.  (You might need to alter the syntax rule as well.)  Not ideal, but not a shelldap issue, as I don't want deletion of a single attribute to wipe a group of them - inconsistent and surprising behavior.

The distributed core.schema:

```
attributetype ( 2.5.4.21 NAME 'telexNumber'
        DESC 'RFC2256: Telex Number'
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.52 )
```

A potential change (your mileage may vary):

```
attributetype ( 2.5.4.21 NAME 'telexNumber'
        DESC 'RFC2256: Telex Number'
        EQUALITY caseIgnoreMatch
        SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{40} )
```

The other LCS issue this made me notice is definitely a shelldap bug, so leaving this ticket to mark that.  Specifically, if the attribute being removed is the last in the list, shelldap doesn't notice the removed line.

**Comment by sigio** [comment]
Ah just my luck, just picked telexNumber as something I could repurpose that I wasn't gonna ever need in it's original purpose ;)

**Comment by mahlonsmith** [comment]
I think this 915f48cca9de56aad4d5dd896e9293b85d8708cc commit squashes the other weird behavior -- I'm guessing "telexNumber" was sorted to the bottom of your entry edit.  You'll still get an error unless that attribute is fixed up server side, but at least now shelldap will relay the correct error (missing equality matcher) vs the strange "no attributes to update" message.
