### ISSUE TITLE
Edit operational attributes

### ISSUE THREAD

**Issue by markfqs** [mahlonsmith/shelldap#8]
Hi,

Although I can view operational Attributes (+), its editing support is not complete (I suppose due schema validation)

I can edit an entry and add operational attribute '`pwdPolicySubentry`'. However, after being added I'm not able anymore to either edit or remove the attribute, as it isn't shown on the editor.

Is there any way to edit operational attributes or planned to implement ?

**Comment by mahlonsmith** [comment]
Hi!

No plans for editing operational attributes, by design they are managed by the directory itself - they aren't supposed to be modified by the user.

Attempts to edit an attribute with NO-USER-MODIFICATION attached results in the following error:

```
[attributeName]: no user modification allowed
```


With that out of the way...  this is a bit of a weird one.  I am guessing you're using OpenLDAP?

It's weird because every operational attribute I've seen is marked -both- as "USAGE directoryOperation", and as NO-USER-MODIFICATION.  The former marks it as operational, the latter ensures that it won't be mucked around with.

For some reason in the ppolicy overlay for OpenLDAP, it doesn't have the NO-USER-MODIFICATION marker.  It's explicit in the source, though it does imply it will be there at a future date:

https://git.openldap.org/openldap/openldap/-/blob/OPENLDAP_REL_ENG_2_4_44/servers/slapd/overlays/ppolicy.c#L174

And sure enough:

```
(  1.3.6.1.4.1.42.2.27.8.1.23
  NAME 'pwdPolicySubentry'
  DESC 'The pwdPolicy subentry in effect for
      this object'
  EQUALITY distinguishedNameMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.12
  SINGLE-VALUE
  USAGE directoryOperation)
```

This means that shelldap won't show it when inspecting the schema (nor editing):

```
~ > inspect pwdPolicy
ObjectClasses:
    pwdPolicy --> top

Attributes:
    pwdAllowUserChange (optional, single-value)
    pwdAttribute (required, multivalue)
    pwdCheckQuality (optional, single-value)
    pwdExpireWarning (optional, single-value)
    pwdFailureCountInterval (optional, single-value)
    pwdGraceAuthNLimit (optional, single-value)
    pwdInHistory (optional, single-value)
    pwdLockout (optional, single-value)
    pwdLockoutDuration (optional, single-value)
    pwdMaxAge (optional, single-value)
    pwdMaxFailure (optional, single-value)
    pwdMaxRecordedFailure (optional, single-value)
    pwdMinAge (optional, single-value)
    pwdMinLength (optional, single-value)
    pwdMustChange (optional, single-value)
    pwdSafeModify (optional, single-value)
```


... but if you add it manually, the server currently allows the edit without error -- though as you've noted, because it's marked operational, it won't show back up in future edits.


`pwdPolicySubentry` is also in a section of the `slapo-policy` docs that states:

```
The operational attributes used by the ppolicy module are stored
in the user's entry.  Most of these attributes are not intended
to be changed directly by users; they are there to track user
activity.  They have been detailed here so that administrators
and users can both understand the workings of the ppolicy module.
```

... so I'm not really sure what the intent is here, or what "Relax control" referenced in the code is all about - but I'm disinclined to hardcode a special case for this strange one-off.

Since the server will allow it, I'd suggest for the time being going outside of shelldap, and just feeding raw LDIF into `ldapmodify` as a workaround, something such as:


```ldif
dn: ...
changetype: modify
modify: pwdPolicySubentry
pwdPolicySubentry: ...
```

Hope that helps!

**Comment by markfqs** [comment]
Makes totally sense. I was aware of the characteristics of operational attributes, but didn't now they were supposed to be read-only.

Thanks for such detailed and well argumented reason.
